spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lowerCaseServiceId: 'true'
server:
  port: '8181'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka