management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: 'false'

spring:
  application:
    name: usuarios-ms
  cloud:
    config:
      uri: http://localhost:8888

server:
  port: '0'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

springdoc:
  swagger-ui:
    path: /